# Generated by Django 3.2.12 on 2024-07-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoderApp', '0004_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='button',
            new_name='button1',
        ),
        migrations.AddField(
            model_name='home',
            name='button2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='button3',
            field=models.CharField(default='', max_length=50),
        ),
    ]
