# Generated by Django 3.2.12 on 2024-07-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icoderApp', '0005_auto_20240705_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='subtitle',
            new_name='sub_title',
        ),
    ]
