# Generated by Django 3.2.12 on 2024-07-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoderApp', '0006_rename_subtitle_home_sub_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('detail', models.TextField()),
                ('image', models.ImageField(default='', upload_to='static/title')),
            ],
        ),
        migrations.RenameField(
            model_name='home',
            old_name='title',
            new_name='Title',
        ),
    ]
